---
version: 2.1

docker_auth: &docker_auth
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest
      auth:
        <<: *docker_auth

jobs:
  lint:
    docker:
      - image: greenpeaceinternational/p4-unit-tests:nodelts
        auth: &docker_auth
    steps:
      - checkout
      - run:
          name: Lint css
          command: npm run lint-css
      - run:
          name: Lint js
          command: npm run lint-js

  promote:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Prepare git
          command: |
            git config user.email "${GIT_USER_EMAIL}"
            git config user.name "CircleCI Bot"
            git config merge.ours.driver true
      - run:
          name: Tag
          command: |
            current_version=$(git-current-tag.sh)
            new_version=$(increment-version.sh $current_version)
            echo "Tagging to ${new_version}"
            git tag -a "$new_version" -m "$new_version"
            git push origin --tags

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Checkout styleguide
          command: git submodule init && git submodule update
      - run:
          name: Activate gcloud
          command: activate-gcloud-account.sh
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Replace static domains
          command: npm run static-prod
      - run:
          name: Build website
          command: npm run publish
      - run:
          name: Publish worker
          command: npx wrangler publish

workflows:
  branch:
    jobs:
      - lint:
          context: cf-workers
      - hold-promote:
          type: approval
          requires:
            - lint
          filters:
            branches:
              only: main
      - promote:
          context: org-global
          requires:
            - hold-promote
          filters:
            branches:
              only: main

  deploy:
    jobs:
      - deploy:
          context:
            - org-global
            - cf-workers
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
