---
version: 2.1

docker_auth: &docker_auth
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

defaults: &defaults
  environment:
      GOOGLE_PROJECT_ID: planet-4-151612
  docker:
    - image: greenpeaceinternational/circleci-base:latest
      auth:
        <<: *docker_auth

jobs:
  lint:
    docker:
      - image: greenpeaceinternational/p4-unit-tests:nodelts
        auth: &docker_auth
    steps:
      - checkout
      - run:
          name: Lint css
          command: npm run lint-css
      - run:
          name: Lint js
          command: npm run lint-js

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Checkout styleguide
          command: git submodule init && git submodule update
      - run:
          name: Activate gcloud
          command: activate-gcloud-account.sh
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Build website
          command: npm run publish
      - run:
          name: Publish worker
          command: npx wrangler publish

workflows:
  branch:
    jobs:
      - lint:
          context: cf-workers

  deploy:
    jobs:
      - deploy:
          context:
            - org-global
            - cf-workers
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
